[build]
  command = "vite build"  # This runs the build using vite, bypassing npm run build
  publish = "dist"        # The directory where the output is stored
  functions = "netlify/functions"  # If you have serverless functions (optional)

[context.production.environment]
  NODE_ENV = "production"
